env:
node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules: {
  linebreak-style:
   - error
   - windows
  ,
  no-console: 0,
  import/extensions:  
    - error
    - ignorePackages
    - js: always
}